- name: Setup base system ready to be used for creating lxd containers
  hosts: master
  gather_facts: yes
  become: false
  become_method: sudo
  vars_files:
    - config.yml

  roles:
    - 00-base
    - role: geerlingguy.ntp
      ntp_manage_config: true
      ntp_servers: [
        clock.sjc.he.net,
        clock.fmt.he.net,
        clock.nyc.he.net
      ]
      become: yes
    - role: geerlingguy.swap
      swap_file_size_mb: '2048'
      become: yes
    - role: 01-lxd-preseed
      tags: preseed
    - role: 02-lxc-launches
      tags: containers
